website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    notes = db.relationship('Note', backref='user')

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DBNAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'onlyfortesting2003'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DBNAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note

    # Creating data base when running app basically
    with app.app_context():
        create_database()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app

def create_database():
    if not path.exists('website/' + DBNAME):
        db.create_all()
        print('Database Created successfully!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
    
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template('loginpage.html', user=current_user)


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif not all([email, first_name, last_name, password1, password2]):
            flash('Please fill in all the fields.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters long.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(last_name) < 2:
            flash('Last name must be greater than 1 character.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, last_name=last_name, password=generate_password_hash(password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account Created!', category='success')
            return redirect(url_for('views.home'))
    return render_template('signup.html', user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Note
from . import db
import json

views = Blueprint('views', __name__)


@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note_content = request.form['note']
        if len(note_content) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note_content, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
        return redirect(url_for('views.home'))

    return render_template('home.html', user=current_user)


@views.route('/')
def landingpage():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    return render_template('landingpage.html', user=current_user)


@views.route('/delete-note', methods=['POST'])
@login_required
def delete_note():
    note = json.loads(request.data) 
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            flash('Note Deleted!', category='error')

    return jsonify({})

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/headerbuttons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/flashmessage.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/note.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{{ url_for('static', filename='script.js') }}"></script>
    <title>{% block title %}{% endblock %} - My Webpage</title>
</head>
<body>
    <header>
        <a href="{{ url_for('views.landingpage') }}" class="logo"></a>
        <div class="header-buttons">
            {% if user.is_authenticated %}
            <a href="/">Home</a>
            <a href="/logout">Logout</a>
            {% else %}
            <a href="/login">Login</a>
            <a href="/signup">Sign Up</a>
            {% endif %}
        </div>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="flash-message {{ category }}">
            {{ message }}
            <button class="close-btn" onclick="this.parentElement.style.display='none';">&times;</button>
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="alldiv">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div style="margin-top: 130px; margin-bottom: 60px;">
    <form style="margin-bottom: 40px;" method="POST">
        <textarea class="note-container" name="note" id="note" placeholder="Write your note here..."></textarea>
        <div>
            <button class="notebtn" type="submit">Save Note</button>
        </div>
    </form>
    <h1 style="text-align: center;">Your Notes</h1>
    <ul class="notes-list">
        {% for note in user.notes %}
        <li>
            <div class="note-content">
                {{ note.data }}
            </div>
            <div>
                <button class="delete-button" onclick="deleteNote({{ note.id }})">Delete</button>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

website/templates/landingpage.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="home-container">
    <h1>Welcome to Your Private Note Keeper</h1>
    <p>Keep your notes safe and organized. Access them from anywhere, anytime.</p>
    <a href="/signup" class="cta-btn">Sign Up Now</a>

    <div class="login-link">
        <p>Already have an account? <a href="/login">Login</a></p>
    </div>
</div>
{% endblock %}

website/templates/loginpage.html
{% extends "base.html" %}

{% block title %}Login Page{% endblock %}

{% block content %}
<div class="login-container">
    <h2>Login</h2>
    <form method="post">
        <label for="email">Email Address<span class="required">*</span></label>
        <input type="email" id="email" name="email" placeholder="Enter email" required>

        <label for="password">Password<span class="required">*</span></label>
        <input type="password" id="password" name="password" placeholder="Enter Password" required>

        <button type="submit" class="submit-btn">Submit</button>
    </form>
</div>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}

{% block title %}Signup Page{% endblock %}

{% block content %}
<div class="signup-container">
    <h2>Sign Up</h2>
    <form method="post">

        <label for="first_name">First Name<span class="required">*</span></label>
        <input type="text" id="first_name" name="first_name" placeholder="Enter first name" required>

        <label for="last_name">Last Name<span class="required">*</span></label>
        <input type="text" id="last_name" name="last_name" placeholder="Enter last name" required>

        <label for="email">Email Address<span class="required">*</span></label>
        <input type="email" id="email" name="email" placeholder="Enter email" required>

        <label for="password1">Password<span class="required">*</span></label>
        <input type="password" id="password1" name="password1" placeholder="Enter password" required>

        <label for="password2">Confirm Password<span class="required">*</span></label>
        <input type="password" id="password2" name="password2" placeholder="Repeat password" required>

        <button type="submit" class="submit-btn">Submit</button>
    </form>
</div>
{% endblock %}